/*
 * File: app/view/Dis_Contact_page.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Dis_Contact_page', {
    extend: 'Ext.Container',

    config: {
        id: 'Dis_Contact_page',
        padding: 25,
        scrollable: true,
        listeners: [
            {
                fn: 'onDis_Contact_pageInitialize',
                event: 'initialize'
            }
        ]
    },

    onDis_Contact_pageInitialize: function(component, eOpts) {
        Ext.ComponentQuery.query('navigationview')[0].getNavigationBar().query('button')[1].show();
    }

});