/*
 * File: app/view/MyPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyPanel', {
    extend: 'Ext.panel.Panel',

    frame: true,
    height: 461,
    width: 759,
    title: 'Template Builder',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'panel',
                    dock: 'left',
                    frame: true,
                    width: 259,
                    collapseFirst: false,
                    collapsed: false,
                    collapsible: true,
                    title: 'Keys',
                    items: [
                        {
                            xtype: 'tabpanel',
                            height: 407,
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'panel',
                                    height: 110,
                                    title: 'Basic',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Background'
                                        },
                                        {
                                            xtype: 'combobox',
                                            fieldLabel: 'Base Font'
                                        },
                                        {
                                            xtype: 'combobox',
                                            fieldLabel: 'Base Languate'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Header',
                                    items: [
                                        {
                                            xtype: 'panel',
                                            height: 245,
                                            id: 'Pan_MainHeader',
                                            width: 263,
                                            title: 'Main Header',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    text: 'HeadTitle',
                                                    listeners: {
                                                        click: {
                                                            fn: me.onButtonClick,
                                                            scope: me
                                                        }
                                                    }
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'Image Header',
                                                    listeners: {
                                                        click: {
                                                            fn: me.onButtonClick1,
                                                            scope: me
                                                        }
                                                    }
                                                },
                                                {
                                                    xtype: 'container',
                                                    autoShow: true,
                                                    id: 'Con_TextOnly',
                                                    items: [
                                                        {
                                                            xtype: 'textfield',
                                                            fieldLabel: 'Label'
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            fieldLabel: 'Color'
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            fieldLabel: 'Align'
                                                        },
                                                        {
                                                            xtype: 'combobox',
                                                            fieldLabel: 'Size'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container',
                                                    id: 'Con_HeadImage',
                                                    style: 'Display:none',
                                                    items: [
                                                        {
                                                            xtype: 'filefield',
                                                            fieldLabel: 'Upload Title Img'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    fieldLabel: 'Header Links'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    fieldLabel: 'BackGround'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'splitter'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Content',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Background'
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Links'
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'paragraphs'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Footer',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Background'
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Links'
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'paragraphs'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            text: 'Change Layout'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            text: 'Save Template',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick2,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'panel',
                    frame: true,
                    height: 445,
                    width: 502,
                    shadow: 'frame',
                    autoScroll: true,
                    collapseFirst: false,
                    title: 'Template Preview',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            height: 31
                        }
                    ],
                    items: [
                        {
                            xtype: 'container',
                            border: 1,
                            frame: true
                        },
                        {
                            xtype: 'container',
                            frame: true
                        },
                        {
                            xtype: 'fieldcontainer',
                            border: 12,
                            height: 127,
                            width: 502,
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            fieldLabel: 'Header'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {

        var myPanel = Ext.getCmp('Pan_MainHeader');
        myPanel.items.items[2].show() //second  item
        myPanel.items.items[3].hide() //second  item
    },

    onButtonClick1: function(button, e, eOpts) {

        var myPanel = Ext.getCmp('Pan_MainHeader');
        myPanel.items.items[2].hide() //second  item
        myPanel.items.items[3].show() //second  item
    },

    onButtonClick2: function(button, e, eOpts) {

    }

});