/*
 * File: app/view/staypage.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.staypage', {
    extend: 'Ext.Container',

    config: {
        id: 'staypage',
        styleHtmlContent: true,
        ui: 'dark',
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'container',
                docked: 'top',
                id: 'iconheader'
            },
            {
                xtype: 'list',
                id: 'Category_List',
                itemId: 'mylist',
                itemTpl: [
                    '<div>',
                    '    {SecondaryCatName}',
                    '    ',
                    '</div>'
                ]
            }
        ],
        listeners: [
            {
                fn: 'onCategory_ListItemTap',
                event: 'itemtap',
                delegate: '#Category_List'
            },
            {
                fn: 'onStaypageInitialize',
                event: 'initialize'
            }
        ]
    },

    onCategory_ListItemTap: function(dataview, index, target, record, e, eOpts) {
        var SecondaryId = record.get('SecondaryId');
        Ext.Msg.confirm("", "Connect to our SavourSQC website to view content?", function(btn){
            if (btn == 'yes'){
                window.location.href = "http://www.savoursqc.com.au/Mobile/ProductList/"+SecondaryId;

            }
        });



    },

    onStaypageInitialize: function(component, eOpts) {
        Ext.ComponentQuery.query('navigationview')[0].getNavigationBar().query('button')[1].show();
    }

});