/*
 * File: app/view/TownsPage.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.TownsPage', {
    extend: 'Ext.Container',

    config: {
        id: 'TownsPage',
        items: [
            {
                xtype: 'container',
                height: 49,
                html: '<img src="images/sbt.png"  />',
                width: 317
            },
            {
                xtype: 'list',
                height: 391,
                id: 'towns_list',
                itemId: 'mylist2',
                itemTpl: [
                    '<div>{TownName}</div>'
                ],
                grouped: true
            }
        ],
        listeners: [
            {
                fn: 'onTownsPageInitialize',
                event: 'initialize'
            },
            {
                fn: 'onTowns_listItemTap',
                event: 'itemtap',
                delegate: '#towns_list'
            }
        ]
    },

    onTownsPageInitialize: function(component, eOpts) {
        Ext.ComponentQuery.query('navigationview')[0].getNavigationBar().query('button')[1].show();
    },

    onTowns_listItemTap: function(dataview, index, target, record, e, eOpts) {
        var TownId = record.get('TownId');
        Ext.Msg.confirm("", "Connect to our SavourSQC website to view content?", function(btn){
            if (btn == 'yes'){
                window.location.href = "http://www.savoursqc.com.au/Mobile/ShowMapbyTown/"+TownId;

            }
        });
    }

});