/*
 * File: app/view/trailspage.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.trailspage', {
    extend: 'Ext.Container',

    config: {
        id: 'trailspage',
        items: [
            {
                xtype: 'container',
                docked: 'top',
                id: 'trailheader'
            },
            {
                xtype: 'list',
                height: 443,
                id: 'trails_list',
                itemId: 'mylist1',
                itemTpl: [
                    '<div>',
                    '    {Journey_title}',
                    '</div>'
                ]
            }
        ],
        listeners: [
            {
                fn: 'onTrails_listItemTap',
                event: 'itemtap',
                delegate: '#trails_list'
            },
            {
                fn: 'onTrailspageInitialize',
                event: 'initialize'
            }
        ]
    },

    onTrails_listItemTap: function(dataview, index, target, record, e, eOpts) {
        var Journey_Id = record.get('Journey_Id');
        Ext.Msg.confirm("", "Connect to our SavourSQC website to view content?", function(btn){
            if (btn == 'yes'){
                window.location.href = "http://www.savoursqc.com.au/Mobile/Trail_Description/"+Journey_Id;

            }
        });
    },

    onTrailspageInitialize: function(component, eOpts) {
        Ext.ComponentQuery.query('navigationview')[0].getNavigationBar().query('button')[1].show();
    }

});