/*
 * File: app/model/Trails.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.Trails', {
    extend: 'Ext.data.Model',

    config: {
        fields: [
            {
                mapping: 'Journey_title',
                name: 'Journey_title',
                type: 'string'
            },
            {
                mapping: 'Journey_Desc',
                name: 'Journey_Desc',
                type: 'string'
            },
            {
                mapping: 'Journey_distance',
                name: 'Journey_distance',
                type: 'string'
            },
            {
                mapping: 'Journey_Id',
                name: 'Journey_Id',
                type: 'string'
            }
        ]
    }
});