/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

//@require @packageOverrides
Ext.Loader.setConfig({

});

Ext.application({
    models: [
        'Category',
        'Trails',
        'Towns'
    ],
    views: [
        'startpage',
        'staypage',
        'placespage',
        'trailspage',
        'TownsPage',
        'Dis_Contact_page'
    ],
    name: 'MyApp',

    launch: function() {
        Ext.Viewport.setMasked({
            //xtype: 'loadmask', 
            //html:'<img height="400" width="300" src="images/startupimage.png">',
            //style: 'background-color: #f7941d'
            style: 'background-image:url(\'images/320x480.png\');'
        });
        new Ext.util.DelayedTask(function () {
            Ext.Viewport.setMasked(false);
            Ext.Viewport.add({
                xclass: 'MyApp.view.startpage'
            });

        }).delay(1000);
    }

});
